"""Cheragh toolkit for standard Python applications.

Imports from the package root are intentionally lazy for heavier integrations and
experimental techniques. Core abstractions are available immediately; everything
else is loaded on first access.
"""
from __future__ import annotations

from importlib import import_module

from .base import (
    BaseRetriever,
    CallableLLMClient,
    Document,
    EmbeddingModel,
    ExtractiveLLMClient,
    HashingEmbedding,
    LLMClient,
    OpenAILLMClient,
    SentenceTransformerEmbedding,
    StaticLLMClient,
)

__version__ = "1.0.0"

_LAZY_EXPORTS = {
    "embedder_fingerprint": (".cache", "embedder_fingerprint"),
    "hash_documents": (".cache", "hash_documents"),
    "load_cache": (".cache", "load_cache"),
    "save_cache": (".cache", "save_cache"),
    "CacheBackend": (".cache", "CacheBackend"),
    "CacheEntry": (".cache", "CacheEntry"),
    "CacheStats": (".cache", "CacheStats"),
    "CacheSerializerError": (".cache", "CacheSerializerError"),
    "MemoryCache": (".cache", "MemoryCache"),
    "SQLiteCache": (".cache", "SQLiteCache"),
    "RedisCache": (".cache.redis", "RedisCache"),
    "build_cache_backend": (".cache", "build_cache_backend"),
    "make_cache_key": (".cache", "make_cache_key"),
    "CachedEmbeddingModel": (".cache", "CachedEmbeddingModel"),
    "CachedRetriever": (".cache", "CachedRetriever"),
    "CachedReranker": (".cache", "CachedReranker"),
    "CachedLLMClient": (".cache", "CachedLLMClient"),
    "cached_call": (".cache", "cached_call"),
    "cache_method": (".cache", "cache_method"),
    "cache_embedding_model": (".cache", "cache_embedding_model"),
    "cache_retriever": (".cache", "cache_retriever"),
    "cache_reranker": (".cache", "cache_reranker"),
    "cache_llm_client": (".cache", "cache_llm_client"),
    "CitationValidationResult": (".citations", "CitationValidationResult"),
    "extract_citations": (".citations", "extract_citations"),
    "validate_citations": (".citations", "validate_citations"),
    "citation_location": (".citations", "citation_location"),
    "ContextCompressor": (".compression", "ContextCompressor"),
    "CompressionPipeline": (".compression", "CompressionPipeline"),
    "ExtractiveContextCompressor": (".compression", "ExtractiveContextCompressor"),
    "RedundancyFilter": (".compression", "RedundancyFilter"),
    "AzureOpenAIEmbedding": (".embeddings", "AzureOpenAIEmbedding"),
    "CohereEmbedding": (".embeddings", "CohereEmbedding"),
    "OpenAIEmbedding": (".embeddings", "OpenAIEmbedding"),
    "VoyageEmbedding": (".embeddings", "VoyageEmbedding"),
    "RAGEngine": (".engine", "RAGEngine"),
    "RAGResponse": (".schema", "RAGResponse"),
    "Source": (".schema", "Source"),
    "Chunk": (".schema", "Chunk"),
    "RetrieverProtocol": (".schema", "RetrieverProtocol"),
    "EmbeddingProtocol": (".schema", "EmbeddingProtocol"),
    "LLMProtocol": (".schema", "LLMProtocol"),
    "RerankerProtocol": (".schema", "RerankerProtocol"),
    "GenerationEvaluationResult": (".evaluation", "GenerationEvaluationResult"),
    "RetrievalEvaluationResult": (".evaluation", "RetrievalEvaluationResult"),
    "RetrievalExample": (".evaluation", "RetrievalExample"),
    "recall_at_k": (".evaluation", "recall_at_k"),
    "ndcg_at_k": (".evaluation", "ndcg_at_k"),
    "context_precision_at_k": (".evaluation", "context_precision_at_k"),
    "evaluate_generation": (".evaluation", "evaluate_generation"),
    "evaluate_pipeline": (".evaluation", "evaluate_pipeline"),
    "evaluate_retrieval": (".evaluation", "evaluate_retrieval"),
    "HybridSearchRetriever": (".hybrid_search", "HybridSearchRetriever"),
    "RetrievalTokenizer": (".tokenization", "RetrievalTokenizer"),
    "tokenize": (".tokenization", "tokenize"),
    "metadata_matches": (".filters", "metadata_matches"),
    "IndexManifest": (".indexing", "IndexManifest"),
    "IndexedFile": (".indexing", "IndexedFile"),
    "IndexOptions": (".indexing", "IndexOptions"),
    "IndexPlan": (".indexing", "IndexPlan"),
    "scan_indexable_files": (".indexing", "scan_indexable_files"),
    "plan_incremental_update": (".indexing", "plan_incremental_update"),
    "index_path": (".indexing", "index_path"),
    "inspect_index": (".indexing", "inspect_index"),
    "load_manifest": (".indexing", "load_manifest"),
    "save_manifest": (".indexing", "save_manifest"),
    "HTMLSectionChunker": (".ingestion", "HTMLSectionChunker"),
    "MarkdownHeaderChunker": (".ingestion", "MarkdownHeaderChunker"),
    "RecursiveTextChunker": (".ingestion", "RecursiveTextChunker"),
    "TextChunk": (".ingestion", "TextChunk"),
    "SentenceWindowChunker": (".ingestion", "SentenceWindowChunker"),
    "SemanticChunker": (".ingestion", "SemanticChunker"),
    "CodeChunker": (".ingestion", "CodeChunker"),
    "TableChunker": (".ingestion", "TableChunker"),
    "PDFLayoutChunker": (".ingestion", "PDFLayoutChunker"),
    "HierarchicalChunker": (".ingestion", "HierarchicalChunker"),
    "TokenTextChunker": (".ingestion", "TokenTextChunker"),
    "chunk_documents": (".ingestion", "chunk_documents"),
    "ingest_path": (".ingestion", "ingest_path"),
    "load_documents": (".ingestion", "load_documents"),
    "AnthropicClient": (".llms", "AnthropicClient"),
    "AzureOpenAIChatClient": (".llms", "AzureOpenAIChatClient"),
    "LiteLLMClient": (".llms", "LiteLLMClient"),
    "OllamaClient": (".llms", "OllamaClient"),
    "OpenAIChatClient": (".llms", "OpenAIChatClient"),
    "AdvancedRAGPipeline": (".pipeline", "AdvancedRAGPipeline"),
    "IdentityQueryTransformer": (".query", "IdentityQueryTransformer"),
    "MultiQueryTransformer": (".query", "MultiQueryTransformer"),
    "QueryTransformer": (".query", "QueryTransformer"),
    "StepBackQueryTransformer": (".query", "StepBackQueryTransformer"),
    "BaseReranker": (".reranking", "BaseReranker"),
    "CohereReranker": (".reranking", "CohereReranker"),
    "CrossEncoderReranker": (".reranking", "CrossEncoderReranker"),
    "KeywordOverlapReranker": (".reranking", "KeywordOverlapReranker"),
    "ReciprocalRankFusionReranker": (".reranking", "ReciprocalRankFusionReranker"),
    "RerankingConfig": (".reranking", "RerankingConfig"),
    "RerankingRetriever": (".reranking", "RerankingRetriever"),
    "build_reranker": (".reranking", "build_reranker"),
    "RAGTrace": (".tracing", "RAGTrace"),
    "RAGTraceStep": (".tracing", "RAGTraceStep"),
    "estimate_tokens": (".tracing", "estimate_tokens"),
    "append_trace_jsonl": (".tracing", "append_trace_jsonl"),
    "ChromaRetriever": (".vectorstores", "ChromaRetriever"),
    "ChromaVectorStore": (".vectorstores", "ChromaVectorStore"),
    "FaissRetriever": (".vectorstores", "FaissRetriever"),
    "FaissVectorStore": (".vectorstores", "FaissVectorStore"),
    "MemoryVectorStore": (".vectorstores", "MemoryVectorStore"),
    "QdrantRetriever": (".vectorstores", "QdrantRetriever"),
    "QdrantVectorStore": (".vectorstores", "QdrantVectorStore"),
    "VectorStoreRetriever": (".vectorstores", "VectorStoreRetriever"),

    "ParentChildIndex": (".retrieval", "ParentChildIndex"),
    "ParentChildRetriever": (".retrieval", "ParentChildRetriever"),
    "CorrectiveRAGEngine": (".corrective", "CorrectiveRAGEngine"),
    "CorrectiveRAGResult": (".corrective", "CorrectiveRAGResult"),
    "RetrievalGrade": (".corrective", "RetrievalGrade"),
    "LexicalRetrievalGrader": (".corrective", "LexicalRetrievalGrader"),
    "ConversationalRAGEngine": (".conversation", "ConversationalRAGEngine"),
    "ConversationTurn": (".conversation", "ConversationTurn"),
    "InMemoryConversationStore": (".conversation", "InMemoryConversationStore"),
    "RAGWorkflow": (".workflow", "RAGWorkflow"),
    "WorkflowResult": (".workflow", "WorkflowResult"),
    "FunctionNode": (".workflow", "FunctionNode"),
    "RetrieveNode": (".workflow", "RetrieveNode"),
    "GenerateNode": (".workflow", "GenerateNode"),
    "TransformQueryNode": (".workflow", "TransformQueryNode"),
    "CompressNode": (".workflow", "CompressNode"),
    "HyDERetriever": (".hyde", "HyDERetriever"),
    "RAGFusionRetriever": (".rag_fusion", "RAGFusionRetriever"),
    "ParentDocumentRetriever": (".parent_document", "ParentDocumentRetriever"),
    "SelfQueryRetriever": (".self_query", "SelfQueryRetriever"),
    "ContextualCompressionRetriever": (".contextual_compression", "ContextualCompressionRetriever"),
    "QueryDecompositionRetriever": (".query_decomposition", "QueryDecompositionRetriever"),
    "StepBackRetriever": (".step_back", "StepBackRetriever"),
    "MMRRetriever": (".mmr", "MMRRetriever"),
    "CorrectiveRAGRetriever": (".corrective_rag", "CorrectiveRAGRetriever"),
    "DocQuality": (".corrective_rag", "DocQuality"),
    "SentenceWindowRetriever": (".sentence_window", "SentenceWindowRetriever"),
    "split_sentences": (".sentence_window", "split_sentences"),
    "HyQERetriever": (".hyqe", "HyQERetriever"),
    "LegacySemanticChunker": (".semantic_chunker", "SemanticChunker"),
    "QueryRouter": (".routing", "QueryRouter"),
    "RoutedResponse": (".routing", "RoutedResponse"),
    "RouteDecision": (".routing", "RouteDecision"),
    "RuleBasedQueryClassifier": (".routing", "RuleBasedQueryClassifier"),
    "KeywordIntentClassifier": (".routing", "KeywordIntentClassifier"),
    "RouteRule": (".routing", "RouteRule"),
    "LegacyRetrieverQueryRouter": (".router", "QueryRouter"),
    "EnsembleRetriever": (".router", "EnsembleRetriever"),
    "MultiHopRAGEngine": (".multihop", "MultiHopRAGEngine"),
    "MultiHopRAGResult": (".multihop", "MultiHopRAGResult"),
    "EvidenceHop": (".multihop", "EvidenceHop"),
    "RuleBasedQueryDecomposer": (".multihop", "RuleBasedQueryDecomposer"),
    "GraphRAGEngine": (".graph", "GraphRAGEngine"),
    "GraphRAGRetriever": (".graph", "GraphRAGRetriever"),
    "KnowledgeGraph": (".graph", "KnowledgeGraph"),
    "KnowledgeTriple": (".graph", "KnowledgeTriple"),
    "RAPTOREngine": (".raptor_engine", "RAPTOREngine"),
    "RAPTORIndex": (".raptor_engine", "RAPTORIndex"),
    "RAPTORNode": (".raptor_engine", "RAPTORNode"),
    "RAPTORRetrieverV2": (".raptor_engine", "RAPTORRetrieverV2"),
    "FederatedRAGEngine": (".federated", "FederatedRAGEngine"),
    "FederatedRAGResult": (".federated", "FederatedRAGResult"),
    "FederatedRetriever": (".federated", "FederatedRetriever"),
    "FederatedSourceResult": (".federated", "FederatedSourceResult"),
    "SQLRAGEngine": (".structured", "SQLRAGEngine"),
    "StructuredRAG": (".structured", "StructuredRAG"),
    "TableSchema": (".structured", "TableSchema"),
    "SQLGenerationResult": (".structured", "SQLGenerationResult"),
    "SQLExecutionResult": (".structured", "SQLExecutionResult"),
    "Principal": (".security", "Principal"),
    "AccessDecision": (".security", "AccessDecision"),
    "AccessPolicy": (".security", "AccessPolicy"),
    "AccessControlledRetriever": (".security", "AccessControlledRetriever"),
    "AccessControlledRAGEngine": (".security", "AccessControlledRAGEngine"),
    "filter_documents_for_principal": (".security", "filter_documents_for_principal"),
    "TenantConfig": (".tenancy", "TenantConfig"),
    "CollectionBinding": (".tenancy", "CollectionBinding"),
    "TenantRegistry": (".tenancy", "TenantRegistry"),
    "MultiTenantRAGEngine": (".tenancy", "MultiTenantRAGEngine"),
    "FeedbackRecord": (".feedback", "FeedbackRecord"),
    "FeedbackSummary": (".feedback", "FeedbackSummary"),
    "InMemoryFeedbackStore": (".feedback", "InMemoryFeedbackStore"),
    "JSONLFeedbackStore": (".feedback", "JSONLFeedbackStore"),
    "FeedbackLoop": (".feedback", "FeedbackLoop"),
    "RAPTORRetriever": (".raptor", "RAPTORRetriever"),
    "FLAREPipeline": (".flare", "FLAREPipeline"),
    "PropositionalRetriever": (".propositional", "PropositionalRetriever"),
    "ChainOfNoteRetriever": (".chain_of_note", "ChainOfNoteRetriever"),
    "AdaptiveRetriever": (".adaptive", "AdaptiveRetriever"),
    "production_hybrid_rag": (".presets", "production_hybrid_rag"),
    "simple_rag": (".presets", "simple_rag"),
    "vector_rag": (".presets", "vector_rag"),
    "strict_rag": (".presets", "strict_rag"),
    "GateDecision": (".adaptive", "GateDecision"),
}


def __getattr__(name: str):
    try:
        module_name, attr = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(name) from exc
    value = getattr(import_module(module_name, __name__), attr)
    globals()[name] = value
    return value


__all__ = [
    "Document",
    "BaseRetriever",
    "LLMClient",
    "EmbeddingModel",
    "HashingEmbedding",
    "SentenceTransformerEmbedding",
    "CallableLLMClient",
    "OpenAILLMClient",
    "StaticLLMClient",
    "ExtractiveLLMClient",
    *_LAZY_EXPORTS.keys(),
]
